export default {
  '0x0000000000000000000000000000000000000000': {
    id: 0,
    token: 'Populous (PPT)',
    description: 'Populous World is creating a platform that allows business to trade invoices on the blockchain. The Populous Platform Tokens serve as a profit sharing mechanism and creates a trading environment for investors and invoice sellers alike.',
    logo: 'https://image.ibb.co/gXaVto/Populous.png',
    discussions: 'https://t.me/populous',
    website: 'https://populous.world/',
  },
  '0x0000000000000000000000000000000000000001': {
    id: 1,
    token: 'District0x (DNT)',
    description: 'District0x is creating a network of marketplaces and communities (“districts”) that exist and interact with each other within the district0x digital environment. Using the DNT token, all ‘citizens’ will be able to post listings, offer skills and create marketplaces for their products and services as fully decentralised autonomous organisations (DAOs).',
    logo: 'https://s2.coinmarketcap.com/static/img/coins/200x200/1856.png',
    discussions: 'https://t.me/district0x',
    website: 'https://district0x.io/',
  },
  '0x0000000000000000000000000000000000000002': {
    id: 2,
    token: 'Melon (MLN)',
    description: 'Melonport is the first of its kind in autonomous systems, designed specifically for the purposes of crypto asset management. They aim to provide a system of tools that empower users to set-up, manage and invest in digital assets.',
    logo: 'https://d33wubrfki0l68.cloudfront.net/a925598e7831981f53d573bb90b63ca172a90726/98ed3/assets/images/loading-logo.png',
    discussions: 'https://t.me/melonport',
    website: 'https://melonport.com/',
  },
  '0x0000000000000000000000000000000000000003': {
    id: 3,
    token: 'Loom (LOOM)',
    description: 'Loom Network is the next-generation blockchain platform for highly scalable games and social apps. The Loom SDK now makes it possible for developers to easily create their own high throughput sidechains or choose to run their DApps on shared chains (such as ZombieChain), all of which are backed by the trust and security of Ethereum.',
    logo: 'https://cdn-images-1.medium.com/max/1200/1*K76UVoLq-FOL7l-_Fag-Qw@2x.png',
    discussions: 'https://loomx.io/',
    website: 'https://loomx.io/',
  },
  '0x0000000000000000000000000000000000000004': {
    id: 4,
    token: 'Autonio (NIO)',
    description: 'AI-powered trading bots for both amateur and professional traders, with truly automated trading and allow users to create their own algorithm as well as connect to their favourite exchange via API.',
    logo: 'https://image.ibb.co/huexke/autonio_logo_white.png',
    discussions: 'https://t.me/Autonio',
    website: 'https://auton.io/',
  },
  '0x0000000000000000000000000000000000000005': {
    id: 5,
    token: 'Sonm (SNM)',
    description: 'Decentralized worldwide fog supercomputer for any general purpose computing from CGI rendering to scientific computations, with global scalability and existing applications including infrastructure for blockchain applications, machine learning, video rendering, site hosting, scientific research, and mining.',
    logo: 'https://image.ibb.co/j4cEyz/SONM.jpg',
    discussion: 'https://t.me/sonm_eng',
    website: 'https://sonm.com/',
  },
  '0x0000000000000000000000000000000000000006': {
    id: 6,
    token: 'Musereum (ETM)',
    description: 'Musereum is creating a platform for music tokenization, copyright sharing and automated licensing. Using an ICO model, they are aiming to build an ecosystem that gives artists new ways to capitalise on their talents whilst preserving their creative license and freedom of expression.',
    logo: 'https://image.ibb.co/b4sX68/Musereum.png',
    discussions: 'https://t.me/joinchat/AxlyZhDrU1JxQeE27eiTVQ',
    website: 'https://musereum.org/',
  },
  '0x0000000000000000000000000000000000000007': {
    id: 7,
    token: 'Digix Gold (DGX)',
    description: 'Digix is a blockchain based platform offering digital tokens backed by 99.99% gold cast bars from London Bullion Market Association-approved refiners. Acting as a digital representation of physical gold, each DGX token represents 1 gram. The transparency, security, traceability of the blockchain ensures that DGX tokens can be transferred with full visibility and auditability.',
    logo: 'https://assets.coingecko.com/coins/images/4171/large/DGX_Token.png?1530715109',
    discussions: 'https://twitter.com/@DigixGlobal',
    website: 'https://digix.global/',
  },
  '0x0000000000000000000000000000000000000008': {
    id: 8,
    token: 'Kleros (PNK)',
    description: 'Blockchain dispute resolution layer that works as decentralised third party to arbitrate disputes, relying on game theoretic incentives to have jurors rule cases correctly in a fast, cheap, reliable and decentralized way.',
    logo: 'https://slack.kleros.io/images/pinakion.png',
    discussion: 'https://t.me/kleros',
    website: 'https://kleros.io/#',
  },
  '0x0000000000000000000000000000000000000009': {
    id: 9,
    token: 'Centrality (CENNZ)',
    description: 'Centrality is a venture studio that partners with leading innovators in key industries to create a marketplace of applications. These applications allow consumers to manage everyday tasks and experiences using peer-to-peer transactions - all via one login and using blockchain-enabled infrastructure.',
    logo: 'https://image.ibb.co/nqYU4T/CENNZ_blue.png',
    discussions: 'https://t.me/centralityofficialtelegram',
    website: 'https://www.centrality.ai',
  },
  '0x0000000000000000000000000000000000000010': {
    id: 10,
    token: 'Banyan Network (BBN)',
    description: 'Bayan Network’s goal is to create a trusted data connection network with third-party data integration, governance, data applications and open market development. They are building a positive and interactive linked-value network by establishing standards, providing channels, and issuing tokens.',
    logo: 'https://image.ibb.co/eLJBzT/Banyan.png',
    discussions: 'https://t.me/BBNGlobalFans',
    website: 'https://www.banyanbbt.org/',
  },
  '0x0000000000000000000000000000000000000011': {
    id: 11,
    token: 'Publica (PBL)',
    description: 'Publica is a platform aiming to revolutionise the publishing industry by offering authors the ability to crowdfunding their works through the blockchain. Utilising smart contracts, Publica’s ecosystem will back the automated performance of agreements like derivative rights for movies, games, and sequels. Readers are able to then fund development of not yet realised works.',
    logo: 'https://cryptoindex.co/coinlogo/publica.png',
    discussions: 'https://t.me/publicaofficial',
    website: 'https://www.exchangeunion.com/',
  },
  '0x0000000000000000000000000000000000000012': {
    id: 12,
    token: 'BankEx (BKX)',
    description: 'BANKEX is developing a solution to transform any asset class into a digital token, providing it with flexiblity, liquidity, and auditability.',
    logo: 'https://s2.coinmarketcap.com/static/img/coins/200x200/2390.png',
    discussions: 'https://bankex.com/',
    website: 'https://bankex.com/',
  },
  '0x0000000000000000000000000000000000000013': {
    id: 13,
    token: 'Civic (CVC)',
    description: 'Civic makes it easy to control and protect your identity with blockchain-powered decentralized authentication solutions, reusable identity elements & KYC tools.',
    logo: 'https://cdn-images-1.medium.com/max/397/1*PnSOAdezv4moUQ2kCuJxCA.png',
    discussions: 'https://t.me/civicplatform',
    website: 'https://www.civic.com/',
  },
};
