import React from 'react';
import Calculator from '../Calculator/Calculator';
import Stats from '../Stats/Stats';
import Voting from '../Voting/Voting';
import './Landing.scss';

export default () => (
  <div className="landing-wrapper">
    <section className="hero">
      <h1>
        welcome to
        <b>
          <span>Nectar</span>
          <span>.community</span>
        </b>
      </h1>
      <div className="hero-footer">
        <div>
          <span className="vertical">scroll down</span>
        </div>
        <div className="text">
          <h2>
            The Ethfinex Nectar token (NEC) is used for governance and entitles the holders to claim
            a share of the fees collected on Ethfinex.
          </h2>
        </div>
        <div />
      </div>
    </section>

    <section className="statistics">
      <div className="container">
        <Stats />
      </div>
    </section>

    <section className="calculator">
      <div className="container">
        <Calculator />
      </div>
    </section>

    <div className="waves" />

    <section className="voting">
      <div className="container">
        <Voting />
      </div>
    </section>

    <div className="waves reverse" />

    <section className="learn-more">
      <div className="container">
        <div className="learn-more-wrapper">
          <div className="bg-text learn-more-bg-text">learn more</div>

          <div className="learn-more-content-wrapper">
            <h1>Learn more</h1>

            <div className="learn-more-content">
              <h2>nectar.community</h2>

              <div className="content-sections">
                <p className="content-section">
                  Ethfinex is the first exchange which will be governed by its community of users,
                  via the Nectar liquidity token (NEC). Nectar.community was created to allow NEC
                  token holders to propose and vote on the future direction and decisions which
                  Ethfinex takes. Traders on Ethfinex earn NEC by adding liquidity, and 50% of the
                  fees generated by trading on Ethfinex are pledged to token holders as ETH.
                </p>
                <p className="content-section">
                  These tools are created open-source to help NEC holders interact safely with the
                  Nectar smart contracts. Over time these will evolve, and open source contributions
                  of new features are welcomed on
                  <a
                    href="http://github.com/ethfinex/community-gateway"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    github
                  </a>
                  .
                </p>
              </div>
            </div>
          </div>

          <div className="find-out-more">
            <div className="desc-text">Find out more about Ethfinex and the Nectar token:</div>

            <div className="links-wrapper">
              <a
                className="logo-link"
                href="https://ethfinex.com"
                target="_blank"
                rel="noopener noreferrer"
              >
                <div className="link-image ethfinex" />
                <div className="link-text">ethfinex.com</div>
              </a>

              <a
                className="logo-link"
                href="https://blog.ethfinex.com"
                target="_blank"
                rel="noopener noreferrer"
              >
                <div className="sub-text-wrapper">
                  <div className="link-image blog" />
                  <div className="sub-text">blog</div>
                </div>
                <div className="link-text">blog.ethfinex.com</div>
              </a>

              <a
                className="logo-link"
                href="https://twitter.com/ethfinex"
                target="_blank"
                rel="noopener noreferrer"
              >
                <div className="link-image twitter" />
                <div className="link-text">twitter</div>
              </a>

              <a
                className="logo-link"
                href="https://support.ethfinex.com"
                target="_blank"
                rel="noopener noreferrer"
              >
                <div className="link-image support" />
                <div className="link-text">support</div>
              </a>

              <a
                className="logo-link"
                href="https://www.youtube.com/channel/UCpPppKXkbJIfSkPKJ5cC_XQ"
                target="_blank"
                rel="noopener noreferrer"
              >
                <div className="link-image youtube" />
                <div className="link-text">youtube</div>
              </a>

              <a
                className="logo-link"
                href="https://github.com/ethfinex"
                target="_blank"
                rel="noopener noreferrer"
              >
                <div className="link-image github" />
                <div className="link-text">github</div>
              </a>
            </div>
          </div>
        </div>
      </div>

      <div className="gradient-section" />
    </section>
  </div>
);
