export default {
  '04/09 - 18/09': {
    listedOn: 'Thursday 20th September',
    winThreshold: 3,
    link: 'https://etherscan.io/token/0xe2d06285211fc0f9cc9d3e62435e474377754478?a=0x2b2d7d874bbfb73f85b2f8a9ee0d9f3e93722622',
    data: [
      {
        id: 0,
        token: 'TaTaTu (TTU)',
        totalYes: 0,
        total: 57236246,
        logo: 'https://s2.coinmarketcap.com/static/img/coins/200x200/2886.png',
        discussions: 'https://t.me/joinchat/GgHdfUhVY-w9zlfwD-jf1Q',
        website: 'https://www.tatatu.com',
      }, {
        id: 1,
        token: 'Content Neutrality Network (CNN)',
        totalYes: 13800000,
        total: 57236246,
        logo: 'https://s2.coinmarketcap.com/static/img/coins/200x200/2735.png',
        discussions: 'https://t.me/cnn_blockchain_official',
        website: 'https://cnntoken.io',
      }, {
        id: 3,
        token: 'VideoCoin (VID)',
        totalYes: 8200000,
        total: 57236246,
        logo: 'https://i.imgur.com/Wf5GvPd.png',
        discussions: 'https://t.me/videocoin',
        website: 'https://www.videocoin.io',
      }, {
        id: 4,
        token: 'Credits (CS)',
        totalYes: 505100,
        total: 57236246,
        logo: 'https://i.imgur.com/whRRJIb.png',
        discussions: 'https://t.me/creditscom',
        website: 'https://credits.com',
      }, {
        id: 5,
        token: 'Contentbox (BOX)',
        totalYes: 26400000,
        total: 57236246,
        logo: 'https://i.imgur.com/2nbWY1t.png',
        discussions: 'https://t.me/BoxCommunity',
        website: 'https://contentbox.one/',
      }, {
        id: 6,
        token: 'OneLedger (OLT)',
        totalYes: 0,
        total: 57236246,
        logo: 'https://s2.coinmarketcap.com/static/img/coins/200x200/2921.png',
        discussions: 'https://t.me/oneledger',
        website: 'https://oneledger.io/',
      }, {
        id: 7,
        token: 'Libra Credit (LBA)',
        totalYes: 0,
        total: 57236246,
        logo: 'https://s2.coinmarketcap.com/static/img/coins/200x200/2760.png',
        discussions: 'https://t.me/oneledger',
        website: 'https://www.libracredit.io/',
      }, {
        id: 8,
        token: 'Yggdrash (YEED)',
        totalYes: 8100000,
        total: 57236246,
        logo: 'https://investment-prod.s3.amazonaws.com/email/ygg/YGG.png',
        discussions: 'https://t.me/joinchat/GjaZ6VEGciYxMNa3pD32hg',
        website: 'https://yggdrash.io/',
      }, {
        id: 9,
        token: 'KIN (KIN)',
        totalYes: 0,
        total: 57236246,
        logo: 'https://www.kik.com/images/kin/kin-logo-onblue.svg',
        discussion: 'https://t.me/kinfoundation',
        website: 'https://www.kik.com/kin/',
      }, {
        id: 10,
        token: 'Bounty0x (BNTY)',
        totalYes: 0,
        total: 57236246,
        logo: 'https://s2.coinmarketcap.com/static/img/coins/200x200/2310.png',
        discussions: 'https://t.me/bounty0x',
        website: 'https://bounty0x.io/',
      }, {
        id: 11,
        token: 'Centrality (CENNZ)',
        totalYes: 0,
        total: 57236246,
        logo: 'https://image.ibb.co/nqYU4T/CENNZ_blue.png',
        discussions: 'https://t.me/centralityofficialtelegram',
        website: 'https://www.centrality.ai',
      }, {
        id: 12,
        token: 'BankEx (BKX)',
        totalYes: 232700,
        total: 57236246,
        logo: 'https://s2.coinmarketcap.com/static/img/coins/200x200/2390.png',
        discussions: 'https://bankex.com/',
        website: 'https://bankex.com/',
      }, {
        id: 13,
        token: 'DragonChain (DRGN)',
        totalYes: 0,
        total: 57236246,
        logo: 'https://dragonchain.com/assets/images/dragon.png',
        discussions: 'https://dragonchain.com/',
        website: 'https://dragonchain.com/',
      },
    ]
  },
  '21/08 - 04/09': {
    listedOn: 'Thursday 6th September',
    winThreshold: 3,
    link: 'https://etherscan.io/token/0x2a509918f8ab6017f8f52d78f8a15e4b29687ad7?a=0x2b2d7d874bbfb73f85b2f8a9ee0d9f3e93722622',
    data: [
      {
        id: 0,
        token: 'Ultra (UTA)',
        totalYes: 30100000,
        total: 126254272,
        logo: 'https://i.imgur.com/NhTTBKB.png',
        discussions: 'https://t.me/ultra_io',
        website: 'https://ultra.io/',
      }, {
        id: 1,
        token: 'Contentbox (BOX)',
        totalYes: 27600000,
        total: 126254272,
        logo: 'https://i.imgur.com/2nbWY1t.png',
        discussions: 'https://t.me/BoxCommunity',
        website: 'https://contentbox.one/',
      }, {
        id: 2,
        token: 'Rate3 (RTE)',
        totalYes: 4900,
        total: 126254272,
        logo: 'https://i.imgur.com/ycazGCt.png',
        discussions: 'https://t.me/OfficialRate3',
        website: 'https://www.rate3.network/',
      }, {
        id: 3,
        token: 'TokenCard (TKN)',
        totalYes: 29000000,
        total: 126254272,
        logo: 'https://i.imgur.com/NfVxEeZ.png',
        discussions: 'https://t.me/TokenCard',
        website: 'https://tokencard.io/',
      }, {
        id: 4,
        token: 'Credits (CS)',
        totalYes: 161300,
        total: 126254272,
        logo: 'https://i.imgur.com/whRRJIb.png',
        discussions: 'https://t.me/creditscom',
        website: 'https://credits.com',
      }, {
        id: 5,
        token: 'Universa (UTNP)',
        totalYes: 31200000,
        total: 126254272,
        logo: 'https://s2.coinmarketcap.com/static/img/coins/200x200/2524.png',
        discussions: 'https://t.me/Uplatform',
        website: 'https://www.universa.io',
      }, {
        id: 6,
        token: 'OneLedger (OLT)',
        totalYes: 0,
        total: 126254272,
        logo: 'https://s2.coinmarketcap.com/static/img/coins/200x200/2921.png',
        discussions: 'https://t.me/oneledger',
        website: 'https://oneledger.io/',
      }, {
        id: 7,
        token: 'Libra Credit (LBA)',
        totalYes: 2900,
        total: 126254272,
        logo: 'https://s2.coinmarketcap.com/static/img/coins/200x200/2760.png',
        discussions: 'https://t.me/oneledger',
        website: 'https://www.libracredit.io/',
      }, {
        id: 8,
        token: 'Yggdrash (YEED)',
        totalYes: 147000,
        total: 126254272,
        logo: 'https://investment-prod.s3.amazonaws.com/email/ygg/YGG.png',
        discussions: 'https://t.me/joinchat/GjaZ6VEGciYxMNa3pD32hg',
        website: 'https://yggdrash.io/',
      }, {
        id: 9,
        token: 'Sonm (SNM)',
        totalYes: 0,
        total: 126254272,
        logo: 'https://image.ibb.co/j4cEyz/SONM.jpg',
        discussion: 'https://t.me/sonm_eng',
        website: 'https://sonm.com/',
      }, {
        id: 10,
        token: 'Bounty0x (BNTY)',
        totalYes: 0,
        total: 126254272,
        logo: 'https://s2.coinmarketcap.com/static/img/coins/200x200/2310.png',
        discussions: 'https://t.me/bounty0x',
        website: 'https://bounty0x.io/',
      }, {
        id: 11,
        token: 'Centrality (CENNZ)',
        totalYes: 0,
        total: 126254272,
        logo: 'https://image.ibb.co/nqYU4T/CENNZ_blue.png',
        discussions: 'https://t.me/centralityofficialtelegram',
        website: 'https://www.centrality.ai',
      }, {
        id: 12,
        token: 'BankEx (BKX)',
        totalYes: 8000000,
        total: 126254272,
        logo: 'https://s2.coinmarketcap.com/static/img/coins/200x200/2390.png',
        discussions: 'https://bankex.com/',
        website: 'https://bankex.com/',
      }, {
        id: 13,
        token: 'Civic (CVC)',
        totalYes: 0,
        total: 126254272,
        logo: 'https://cdn-images-1.medium.com/max/397/1*PnSOAdezv4moUQ2kCuJxCA.png',
        discussions: 'https://t.me/civicplatform',
        website: 'https://www.civic.com/',
      },
    ]
  },
  '07/08 - 21/08': {
    listedOn: 'Thursday 23rd August',
    winThreshold: 3,
    link: 'https://etherscan.io/token/0xf5490dd02ef9a20682fa7cd12fd2be428b5a2431?a=0x2b2d7d874bbfb73f85b2f8a9ee0d9f3e93722622',
    data: [
      {
        id: 0,
        token: 'Populous (PPT)',
        totalYes: 0,
        total: 91194189,
        logo: 'https://image.ibb.co/gXaVto/Populous.png',
        discussions: 'https://t.me/populous',
        website: 'https://populous.world/',
      }, {
        id: 1,
        token: 'District0x (DNT)',
        totalYes: 0,
        total: 91194189,
        logo: 'https://s2.coinmarketcap.com/static/img/coins/200x200/1856.png',
        discussions: 'https://t.me/district0x',
        website: 'https://district0x.io/',
      }, {
        id: 2,
        token: 'Melon (MLN)',
        totalYes: 15400000,
        total: 91194189,
        logo: 'https://d33wubrfki0l68.cloudfront.net/a925598e7831981f53d573bb90b63ca172a90726/98ed3/assets/images/loading-logo.png',
        discussions: 'https://t.me/melonport',
        website: 'https://melonport.com/',
      }, {
        id: 3,
        token: 'Loom (LOOM)',
        totalYes: 0,
        total: 91194189,
        logo: 'https://cdn-images-1.medium.com/max/1200/1*K76UVoLq-FOL7l-_Fag-Qw@2x.png',
        discussions: 'https://loomx.io/',
        website: 'https://loomx.io/',
      }, {
        id: 4,
        token: 'Autonio (NIO)',
        totalYes: 26000000,
        total: 91194189,
        logo: 'https://image.ibb.co/huexke/autonio_logo_white.png',
        discussions: 'https://t.me/Autonio',
        website: 'https://auton.io/',
      }, {
        id: 5,
        token: 'Sonm (SNM)',
        totalYes: 475.7,
        total: 91194189,
        logo: 'https://image.ibb.co/j4cEyz/SONM.jpg',
        discussion: 'https://t.me/sonm_eng',
        website: 'https://sonm.com/',
      }, {
        id: 6,
        token: 'Musereum (ETM)',
        totalYes: 0,
        total: 91194189,
        logo: 'https://image.ibb.co/b4sX68/Musereum.png',
        discussions: 'https://t.me/joinchat/AxlyZhDrU1JxQeE27eiTVQ',
        website: 'https://musereum.org/',
      }, {
        id: 7,
        token: 'Digix Gold (DGX)',
        totalYes: 20300000,
        total: 91194189,
        logo: 'https://assets.coingecko.com/coins/images/4171/large/DGX_Token.png?1530715109',
        discussions: 'https://twitter.com/@DigixGlobal',
        website: 'https://digix.global/',
      }, {
        id: 8,
        token: 'Kleros (PNK)',
        totalYes: 0,
        total: 91194189,
        logo: 'https://slack.kleros.io/images/pinakion.png',
        discussion: 'https://t.me/kleros',
        website: 'https://kleros.io/#',
      }, {
        id: 9,
        token: 'Centrality (CENNZ)',
        totalYes: 63500,
        total: 91194189,
        logo: 'https://image.ibb.co/nqYU4T/CENNZ_blue.png',
        discussions: 'https://t.me/centralityofficialtelegram',
        website: 'https://www.centrality.ai',
      }, {
        id: 10,
        token: 'Banyan Network (BBN)',
        totalYes: 26200000,
        total: 91194189,
        logo: 'https://image.ibb.co/eLJBzT/Banyan.png',
        discussions: 'https://t.me/BBNGlobalFans',
        website: 'https://www.banyanbbt.org/',
      }, {
        id: 11,
        token: 'Publica (PBL)',
        totalYes: 0,
        total: 91194189,
        logo: 'https://cryptoindex.co/coinlogo/publica.png',
        discussions: 'https://t.me/publicaofficial',
        website: 'https://www.exchangeunion.com/',
      }, {
        id: 12,
        token: 'BankEx (BKX)',
        totalYes: 2700000,
        total: 91194189,
        logo: 'https://s2.coinmarketcap.com/static/img/coins/200x200/2390.png',
        discussions: 'https://bankex.com/',
        website: 'https://bankex.com/',
      }, {
        id: 13,
        token: 'Civic (CVC)',
        totalYes: 0,
        total: 91194189,
        logo: 'https://cdn-images-1.medium.com/max/397/1*PnSOAdezv4moUQ2kCuJxCA.png',
        discussions: 'https://t.me/civicplatform',
        website: 'https://www.civic.com/',
      },
    ]
  },
  '24/07 - 07/08': {
    listedOn: 'Thursday 9th August',
    winThreshold: 3,
    link: 'https://etherscan.io/token/0x448e0fed8d5b6494d75412a1a263ae3bbfbb505f?a=0x2b2d7d874bbfb73f85b2f8a9ee0d9f3e93722622',
    data: [
      {
        id: 0,
        token: 'Populous (PPT)',
        totalYes: 0,
        total: 113223942,
        logo: 'https://image.ibb.co/gXaVto/Populous.png',
        discussions: 'https://t.me/populous',
        website: 'https://populous.world/',
      }, {
        id: 1,
        token: 'District0x (DNT)',
        totalYes: 9800,
        total: 113223942,
        logo: 'https://s2.coinmarketcap.com/static/img/coins/200x200/1856.png',
        discussions: 'https://t.me/district0x',
        website: 'https://district0x.io/',
      }, {
        id: 2,
        token: 'Melon (MLN)',
        totalYes: 8500,
        total: 113223942,
        logo: 'https://d33wubrfki0l68.cloudfront.net/a925598e7831981f53d573bb90b63ca172a90726/98ed3/assets/images/loading-logo.png',
        discussions: 'https://t.me/melonport',
        website: 'https://melonport.com/',
      }, {
        id: 3,
        token: 'Fantom (FTM)',
        totalYes: 0,
        total: 113223942,
        logo: 'https://i.imgur.com/W5Rv0SY.png',
        discussions: 'https://t.me/Fantom_English',
        website: 'https://www.fantom.foundation',
      }, {
        id: 4,
        token: 'BlockPass (PASS)',
        totalYes: 29900000,
        total: 113223942,
        logo: 'https://miro.medium.com/fit/c/240/240/1*JrzELkcCFLgUzMhp5TD1dg.png',
        discussions: 'https://t.me/blockpass',
        website: 'https://blockpass.org/',
      }, {
        id: 5,
        token: 'Walton (WTC)',
        totalYes: 0,
        total: 113223942,
        logo: 'https://s2.coinmarketcap.com/static/img/coins/200x200/1925.png',
        discussions: 'https://www.reddit.com/r/waltonchain/',
        website: 'https://www.waltonchain.org/',
      }, {
        id: 6,
        token: 'Musereum (ETM)',
        totalYes: 0,
        total: 113223942,
        logo: 'https://image.ibb.co/b4sX68/Musereum.png',
        discussions: 'https://t.me/joinchat/AxlyZhDrU1JxQeE27eiTVQ',
        website: 'https://musereum.org/',
      }, {
        id: 7,
        token: 'Digix Gold (DGX)',
        totalYes: 5500000,
        total: 113223942,
        logo: 'https://assets.coingecko.com/coins/images/4171/large/DGX_Token.png?1530715109',
        discussions: 'https://twitter.com/@DigixGlobal',
        website: 'https://digix.global/',
      }, {
        id: 8,
        token: 'MATRIX (MAN)',
        totalYes: 30000000,
        total: 113223942,
        logo: 'https://cryptoindex.co/coinlogo/matrix-ai-network.png',
        discussions: 'https://t.me/matrixainetwork',
        website: 'https://www.matrix.io/',
      }, {
        id: 9,
        token: 'Zebi (ZCO)',
        totalYes: 0,
        total: 113223942,
        logo: 'https://cryptoindex.co/coinlogo/zebi.png',
        discussions: 'https://t.me/ZebiData',
        website: 'https://www.zebi.io',
      }, {
        id: 10,
        token: 'Banyan Network (BBN)',
        totalYes: 38000,
        total: 113223942,
        logo: 'https://image.ibb.co/eLJBzT/Banyan.png',
        discussions: 'https://t.me/BBNGlobalFans',
        website: 'https://www.banyanbbt.org/',
      }, {
        id: 11,
        token: 'Publica (PBL)',
        totalYes: 5200,
        total: 113223942,
        logo: 'https://cryptoindex.co/coinlogo/publica.png',
        discussions: 'https://t.me/publicaofficial',
        website: 'https://www.exchangeunion.com/',
      }, {
        id: 12,
        token: 'The Abyss (ABYSS)',
        totalYes: 30100000,
        total: 113223942,
        logo: 'https://image.ibb.co/kHWSR8/256_R.png',
        discussions: 'https://t.me/theabyss',
        website: 'https://www.theabyss.com/',
      }, {
        id: 13,
        token: 'Ethos (ETHOS)',
        totalYes: 17600000,
        total: 113223942,
        logo: 'https://image.ibb.co/j2fCC8/Ethos_Logo_white_knockout.png',
        discussions: 'https://www.ethos.io/',
        website: 'https://www.ethos.io/',
      },
    ]
  },
  '10/07 - 24/07': {
    listedOn: 'Thursday 26th July',
    winThreshold: 3,
    link: 'https://etherscan.io/token/0x4237e70f7ebb2ca125a85f97288cc6ad0c2c40b6?a=0x2b2d7d874bbfb73f85b2f8a9ee0d9f3e93722622',
    data: [
      {
        id: 0,
        token: 'Aeternity (AE)',
        totalYes: 0,
        total: 87270648,
        logo: 'https://logos-download.com/wp-content/uploads/2018/05/Aeternity_logo_coin.png',
        discussions: 'https://www.ethfinex.com/token_listings/49/social_category/292/AE',
        website: 'https://aeternity.com/',
      }, {
        id: 1,
        token: 'Republic Protocol (REN)',
        totalYes: 0,
        total: 87270648,
        logo: 'https://s2.coinmarketcap.com/static/img/coins/200x200/2539.png',
        discussions: 'https://republicprotocol.com/',
        website: 'https://republicprotocol.com/',
      }, {
        id: 2,
        token: 'Bancor (BNT)',
        totalYes: 13700000,
        total: 87270648,
        logo: 'https://cdn.freebiesupply.com/logos/large/2x/bancor-2-logo-png-transparent.png',
        discussions: 'https://www.reddit.com/r/Bancor/',
        website: 'https://bancor.network/',
      }, {
        id: 3,
        token: 'Fantom (FTM)',
        totalYes: 0,
        total: 87270648,
        logo: 'https://i.imgur.com/W5Rv0SY.png',
        discussions: 'https://t.me/Fantom_English',
        website: 'https://www.fantom.foundation',
      }, {
        id: 4,
        token: 'Zilliqa (ZIL)',
        totalYes: 17900000,
        total: 87270648,
        logo: 'https://seeklogo.com/images/Z/zilliqa-logo-3AF6BFB223-seeklogo.com.png',
        discussions: 'https://twitter.com/zilliqa',
        website: 'https://zilliqa.com/',
      }, {
        id: 5,
        token: 'Walton (WTC)',
        totalYes: 1000000,
        total: 87270648,
        logo: 'https://s2.coinmarketcap.com/static/img/coins/200x200/1925.png',
        discussions: 'https://www.reddit.com/r/waltonchain/',
        website: 'https://www.waltonchain.org/',
      }, {
        id: 6,
        token: 'Stox (STX)',
        totalYes: 11900000,
        total: 87270648,
        logo: 'https://coinnext.net/wp-content/uploads/2017/12/stox.png',
        discussions: 'https://www.stox.com/',
        website: 'https://www.stox.com/',
      }, {
        id: 7,
        token: 'Enigma (ENG)',
        totalYes: 0,
        total: 87270648,
        logo: 'https://s2.coinmarketcap.com/static/img/coins/200x200/2044.png',
        discussions: 'https://www.reddit.com/r/EnigmaProject/',
        website: 'https://enigma.co/',
      }, {
        id: 8,
        token: 'Ethos (ETHOS)',
        totalYes: 7700000,
        total: 87270648,
        logo: 'https://image.ibb.co/j2fCC8/Ethos_Logo_white_knockout.png',
        discussions: 'https://www.ethos.io/',
        website: 'https://www.ethos.io/',
      }, {
        id: 9,
        token: 'WePower (WPR)',
        totalYes: 35000000,
        total: 87270648,
        logo: 'https://image.ibb.co/dzfCXJ/Wepower_logo_256x256.png',
        discussions: 'https://t.me/WePowerNetwork',
        website: 'https://wepower.network/',
      }, {
        id: 10,
        token: 'Naga (NGC)',
        totalYes: 10100,
        total: 87270648,
        logo: 'https://i.vimeocdn.com/portrait/21759767_300x300',
        discussions: 'https://t.me/official_nagacoin',
        website: 'https://naga.com/coin/',
      }, {
        id: 11,
        token: 'Exchange Union (XUC)',
        totalYes: 3300,
        total: 87270648,
        logo: 'https://seeklogo.com/images/E/exchange-union-xuc-logo-D69254C1A4-seeklogo.com.png',
        discussions: 'https://www.exchangeunion.com/',
        website: 'https://www.exchangeunion.com/',
      }, {
        id: 12,
        token: 'Chainlink (LINK)',
        totalYes: 519,
        total: 87270648,
        logo: 'https://cdn.worldvectorlogo.com/logos/chainlink-1.svg',
        discussions: 'https://telegram.me/chainlink',
        website: 'https://www.smartcontract.com/link#chainlink',
      }, {
        id: 13,
        token: 'Nebulas (NAS)',
        totalYes: 0,
        total: 87270648,
        logo: 'http://icons.iconarchive.com/icons/cjdowner/cryptocurrency-flat/1024/Nebulas-NAS-icon.png',
        discussions: 'https://t.me/nebulasio',
        website: 'https://nebulas.io/',
      },
    ],
  },
  '26/06 - 10/07': {
    listedOn: 'Thursday 13th July',
    winThreshold: 3,
    link: 'https://etherscan.io/token/0x1da899dfba6cca073a5283f1855453ebfd13ecfb?a=0x2b2d7d874bbfb73f85b2f8a9ee0d9f3e93722622',
    data: [
      {
        id: 0,
        token: 'Loom',
        totalYes: 860,
        total: 88883844,
        logo: 'https://cdn-images-1.medium.com/max/1200/1*K76UVoLq-FOL7l-_Fag-Qw@2x.png',
        discussions: 'https://loomx.io/',
        website: 'https://loomx.io/',
      }, {
        id: 1,
        token: 'Data (DTA)',
        totalYes: 21100000,
        total: 88883844,
        logo: 'https://data.eco/images/logo.DATA.svg',
        discussions: 'https://data.eco/',
        website: 'https://data.eco/',
      }, {
        id: 2,
        token: 'Republic Protocol',
        totalYes: 10300000,
        total: 88883844,
        logo: 'https://s2.coinmarketcap.com/static/img/coins/200x200/2539.png',
        discussions: 'https://republicprotocol.com/',
        website: 'https://republicprotocol.com/',
      }, {
        id: 3,
        token: 'Kin',
        totalYes: 528,
        total: 88883844,
        logo: 'https://www.kik.com/images/kin/kin-logo-onblue.svg',
        discussions: 'https://www.ethfinex.com/token_listings/25/social_category/146/KIN',
        website: 'https://www.kik.com/kin/',
      }, {
        id: 4,
        token: 'DragonChain',
        totalYes: 13800000,
        total: 88883844,
        logo: 'https://dragonchain.com/assets/images/dragon.png',
        discussions: 'https://www.ethfinex.com/token_listings/13/social_category/76/DRGN',
        website: 'https://dragonchain.com/',
      }, {
        id: 5,
        token: 'Hydro Protocol',
        totalYes: 24300000,
        total: 88883844,
        logo: 'https://www.currencycalculate.com/res/img/cryptocurrencies/hydro-protocol.png',
        discussions: 'https://thehydrofoundation.com/',
        website: 'https://thehydrofoundation.com/',
      }, {
        id: 6,
        token: 'Hubii',
        totalYes: 12300,
        total: 88883844,
        logo: 'https://cdn-images-1.medium.com/max/1600/0*NVI3KkOEvbz0_Ff0.',
        discussions: 'https://www.ethfinex.com/token_listings/36/social_category/212/HBT',
        website: 'https://www.hubii.com/',
      }, {
        id: 7,
        token: 'Stox',
        totalYes: 672,
        total: 88883844,
        logo: 'https://coinnext.net/wp-content/uploads/2017/12/stox.png',
        discussions: 'https://www.stox.com/',
        website: 'https://www.stox.com/',
      }, {
        id: 8,
        token: 'Lala World',
        totalYes: 0,
        total: 88883844,
        logo: 'https://en.bitcoinwiki.org/upload/en/images/thumb/9/98/LaLa_World_Logo.png/300px-LaLa_World_Logo.png',
        discussions: 'https://www.ethfinex.com/token_listings/34/social_category/200/LALA',
        website: 'https://lalaworld.io/',
      }, {
        id: 9,
        token: 'Ethos',
        totalYes: 0,
        total: 88883844,
        logo: 'https://image.ibb.co/j2fCC8/Ethos_Logo_white_knockout.png',
        discussions: 'https://www.ethos.io/',
        website: 'https://www.ethos.io/',
      }, {
        id: 10,
        token: 'IPSX',
        totalYes: 0,
        total: 88883844,
        logo: 'https://cryptoindex.co/coinlogo/ip-exchange.png',
        discussions: 'https://www.ipsx.com/',
        website: 'https://www.ipsx.com/',
      }, {
        id: 11,
        token: 'Human Protocol',
        totalYes: 18500000,
        total: 88883844,
        logo: 'https://hcaptcha.com/static/img/site/human-token.png',
        discussions: 'https://hcaptcha.com/',
        website: 'https://hcaptcha.com/',
      }, {
        id: 12,
        token: 'Naga',
        totalYes: 0,
        total: 88883844,
        logo: 'https://i.vimeocdn.com/portrait/21759767_300x300',
        discussions: 'https://naga.com/coin/',
        website: 'https://naga.com/coin/',
      }, {
        id: 13,
        token: 'Exchange Union',
        totalYes: 0,
        total: 88883844,
        logo: 'https://seeklogo.com/images/E/exchange-union-xuc-logo-D69254C1A4-seeklogo.com.png',
        discussions: 'https://www.exchangeunion.com/',
        website: 'https://www.exchangeunion.com/',
      },
    ]
  },
  '12/06 - 26/06': {
    listedOn: 'Thursday 28th June',
    winThreshold: 4,
    link: 'https://etherscan.io/token/0x99ee6275a7ec7165c63fb7cfeb8b8e1a73722733?a=0x2b2d7d874bbfb73f85b2f8a9ee0d9f3e93722622',
    data: [
      {
        id: 0,
        token: 'Loom',
        totalYes: 2500000,
        total: 66187336,
        logo: 'https://cdn-images-1.medium.com/max/1200/1*K76UVoLq-FOL7l-_Fag-Qw@2x.png',
        discussions: 'https://loomx.io/',
        website: 'https://loomx.io/',
      }, {
        id: 1,
        token: 'Cortex',
        totalYes: 12400000,
        total: 66187336,
        logo: 'http://www.cortexlabs.ai/cortexImg/logo.png',
        discussions: 'http://www.cortexlabs.ai/',
        website: 'http://www.cortexlabs.ai/',
      }, {
        id: 2,
        token: 'Republic Protocol',
        totalYes: 19900,
        total: 66187336,
        logo: 'https://s2.coinmarketcap.com/static/img/coins/200x200/2539.png',
        discussions: 'https://republicprotocol.com/',
        website: 'https://republicprotocol.com/',
      }, {
        id: 3,
        token: 'Edenchain',
        totalYes: 0,
        total: 66187336,
        logo: 'https://edenchain.io/wp-content/uploads/2018/06/edenmain.png',
        discussions: 'https://edenchain.io/',
        website: 'https://edenchain.io/',
      }, {
        id: 4,
        token: 'Icon',
        totalYes: 8500,
        total: 66187336,
        logo: 'https://coinmarketdaddy.com/upload/coin/11523185991.png',
        discussions: 'https://icon.foundation/',
        website: 'https://icon.foundation/',
      }, {
        id: 5,
        token: 'BlockEx',
        totalYes: 8000000,
        total: 66187336,
        logo: 'https://image.ibb.co/dGCsSd/logo_png_rj.png',
        discussions: 'https://daxt.io/',
        website: 'https://daxt.io/',
      }, {
        id: 6,
        token: 'Hydro Protocol',
        totalYes: 0,
        total: 661873360,
        logo: 'https://www.currencycalculate.com/res/img/cryptocurrencies/hydro-protocol.png',
        discussions: 'https://thehydrofoundation.com/',
        website: 'https://thehydrofoundation.com/',
      }, {
        id: 7,
        token: 'Cindicator',
        totalYes: 10800000,
        total: 66187336,
        logo: 'https://coinlookup.co/wp-content/uploads/2018/03/cindicator.png',
        discussions: 'https://cindicator.com/',
        website: 'https://cindicator.com/',
      }, {
        id: 8,
        token: 'Nucleus Vision',
        totalYes: 12600000,
        total: 66187336,
        logo: 'https://www.bitprime.co.nz/wp-content/uploads/2018/03/NCASH.png',
        discussions: 'https://nucleus.vision/',
        website: 'https://nucleus.vision/',
      }, {
        id: 9,
        token: 'Stox',
        totalYes: 7100000,
        total: 66187336,
        logo: 'https://coinnext.net/wp-content/uploads/2017/12/stox.png',
        discussions: 'https://www.stox.com/',
        website: 'https://www.stox.com/',
      }, {
        id: 10,
        token: 'Lala World',
        totalYes: 0,
        total: 66187336,
        logo: 'https://en.bitcoinwiki.org/upload/en/images/thumb/9/98/LaLa_World_Logo.png/300px-LaLa_World_Logo.png',
        discussions: 'https://www.ethfinex.com/token_listings/34/social_category/200/LALA',
        website: 'https://lalaworld.io/',
      }, {
        id: 11,
        token: 'Consensus AI',
        totalYes: 12700000,
        total: 66187336,
        logo: 'https://consensus.ai/launch/images/sign.svg',
        discussions: 'https://www.ethfinex.com/token_listings/47/social_category/281/SEN',
        website: 'https://consensus.ai/',
      },
    ]
  },
  '29/05 - 12/06': {
    listedOn: 'Thursday 14th June',
    winThreshold: 4,
    link: 'https://etherscan.io/token/0xd7e7a876058d8e67efb26ad7b10a4007d90396bc?a=0x2b2d7d874bbfb73f85b2f8a9ee0d9f3e93722622',
    data: [
      {
        id: 0,
        token: 'Wings',
        totalYes: 396.7,
        total: 59384496,
        logo: 'https://www.cryptocompare.com/media/1382758/1wings.png',
        discussions: 'https://www.ethfinex.com/token_listings/10/social_category/59/WINGS',
        website: 'https://www.wings.ai/',
      }, {
        id: 1,
        token: 'Auctus',
        totalYes: 15500000,
        total: 59384496,
        logo: 'https://s2.coinmarketcap.com/static/img/coins/200x200/2653.png',
        discussions: 'https://www.ethfinex.com/token_listings/45/social_category/269/AUC',
        website: 'https://auctus.org/',
      }, {
        id: 2,
        token: 'Cindicator',
        totalYes: 146500,
        total: 59384496,
        logo: 'https://coinlookup.co/wp-content/uploads/2018/03/cindicator.png',
        discussions: 'https://cindicator.com/',
        website: 'https://cindicator.com/',
      }, {
        id: 3,
        token: 'Internet Node Token',
        totalYes: 0,
        total: 59384496,
        logo: 'https://s2.coinmarketcap.com/static/img/coins/200x200/2399.png',
        discussions: 'https://www.ethfinex.com/token_listings/30/social_category/179/INT',
        website: 'https://intchain.io/',
      }, {
        id: 4,
        token: 'Icon',
        totalYes: 1000,
        total: 59384496,
        logo: 'https://coinmarketdaddy.com/upload/coin/11523185991.png',
        discussions: 'https://icon.foundation/',
        website: 'https://icon.foundation/',
      }, {
        id: 5,
        token: 'BlockEx',
        totalYes: 436500,
        total: 59384496,
        logo: 'https://image.ibb.co/dGCsSd/logo_png_rj.png',
        discussions: 'https://daxt.io/',
        website: 'https://daxt.io/',
      }, {
        id: 6,
        token: 'Polymath',
        totalYes: 13800000,
        total: 59384496,
        logo: 'https://global-uploads.webflow.com/5a46fad33472ef00014b540a/5a46fad33472ef00014b5453_Polymath-Logos_Color_r5.svg',
        discussions: 'https://www.polymath.network/',
        website: 'https://www.polymath.network/',
      }, {
        id: 7,
        token: 'Fusion',
        totalYes: 10800000,
        total: 59384496,
        logo: 'https://s2.coinmarketcap.com/static/img/coins/200x200/2530.png',
        discussions: 'https://www.fusion.org/',
        website: 'https://www.fusion.org/',
      }, {
        id: 8,
        token: 'DragonChain',
        totalYes: 4500000,
        total: 59384496,
        logo: 'https://dragonchain.com/assets/images/dragon.png',
        discussions: 'https://www.ethfinex.com/token_listings/13/social_category/76/DRGN',
        website: 'https://dragonchain.com/',
      }, {
        id: 9,
        token: 'CommerceBlock',
        totalYes: 7800000,
        total: 59384496,
        logo: 'https://www.commerceblock.com/wp-content/themes/commerceblock/public/img/int/logo-small.png',
        discussions: 'https://www.commerceblock.com/',
        website: 'https://www.commerceblock.com/',
      }, {
        id: 10,
        token: 'Hubii',
        totalYes: 6400000,
        total: 59384496,
        logo: 'https://cdn-images-1.medium.com/max/1600/0*NVI3KkOEvbz0_Ff0.',
        discussions: 'https://www.ethfinex.com/token_listings/36/social_category/212/HBT',
        website: 'https://www.hubii.com/',
      }, {
        id: 11,
        token: 'Aeternity',
        totalYes: 100,
        total: 59384496,
        logo: 'https://logos-download.com/wp-content/uploads/2018/05/Aeternity_logo_coin.png',
        discussions: 'https://www.ethfinex.com/token_listings/49/social_category/292/AE',
        website: 'https://aeternity.com/',
      },
    ]
  },
  '15/05 - 29/05': {
    listedOn: 'Thursday 31st May',
    winThreshold: 4,
    link: 'https://etherscan.io/address/0x64575dc58f1927dbf5633b3168d55a0012da340c#tokentxns',
    data: [
      {
        id: 0,
        token: 'Wings',
        totalYes: 2300000,
        total: 45471000,
        logo: 'https://www.cryptocompare.com/media/1382758/1wings.png',
        discussions: 'https://www.ethfinex.com/token_listings/10/social_category/59/WINGS',
        website: 'https://www.wings.ai/',
      }, {
        id: 1,
        token: 'Auctus',
        totalYes: 1100000,
        total: 45471000,
        logo: 'https://s2.coinmarketcap.com/static/img/coins/200x200/2653.png',
        discussions: 'https://www.ethfinex.com/token_listings/45/social_category/269/AUC',
        website: 'https://auctus.org/',
      }, {
        id: 2,
        token: 'Polymath',
        totalYes: 5100000,
        total: 45471000,
        logo: 'https://global-uploads.webflow.com/5a46fad33472ef00014b540a/5a46fad33472ef00014b5453_Polymath-Logos_Color_r5.svg',
        discussions: 'https://www.polymath.network/',
        website: 'https://www.polymath.network/',
      }, {
        id: 3,
        token: 'BlockV',
        totalYes: 6300000,
        total: 45471000,
        logo: 'https://getcrypto.info/blockv/images/logo.png',
        discussions: 'https://www.ethfinex.com/token_listings/33/social_category/197/VEE',
        website: 'https://blockv.io/',
      }, {
        id: 4,
        token: 'DragonChain',
        totalYes: 5500000,
        total: 45471000,
        logo: 'https://dragonchain.com/assets/images/dragon.png',
        discussions: 'https://www.ethfinex.com/token_listings/13/social_category/76/DRGN',
        website: 'https://dragonchain.com/',
      }, {
        id: 5,
        token: 'Kin',
        totalYes: 5000000,
        total: 45471000,
        logo: 'https://www.kik.com/images/kin/kin-logo-onblue.svg',
        discussions: 'https://www.ethfinex.com/token_listings/25/social_category/146/KIN',
        website: 'https://www.kik.com/kin/',
      }, {
        id: 6,
        token: 'Internet Node Token',
        totalYes: 535000,
        total: 45471000,
        logo: 'https://s2.coinmarketcap.com/static/img/coins/200x200/2399.png',
        discussions: 'https://www.ethfinex.com/token_listings/30/social_category/179/INT',
        website: 'https://intchain.io/',
      }, {
        id: 7,
        token: 'Dadi',
        totalYes: 5800000,
        total: 45471000,
        logo: 'https://s2.coinmarketcap.com/static/img/coins/200x200/2535.png',
        discussions: 'https://dadi.cloud/',
        website: 'https://dadi.cloud/',
      }, {
        id: 8,
        token: 'Utrust',
        totalYes: 6500000,
        total: 45471000,
        logo: 'https://s2.coinmarketcap.com/static/img/coins/200x200/2320.png',
        discussions: 'https://www.ethfinex.com/token_listings/35/social_category/209/UTRUST',
        website: 'https://utrust.io/',
      }, {
        id: 9,
        token: 'Lympo',
        totalYes: 7400000,
        total: 45471000,
        logo: 'https://cryptocoincharts.info/img/coins/lym.svg',
        discussions: 'https://lympo.io/',
        website: 'https://lympo.io/',
      },
    ]
  }
};
